### ISSUE TITLE
selenium 練習用

### ISSUE THREAD

**Issue by masakura** [yamachiii/test#1]
まさくらです。連絡先がわからないのでこちらで。

Selenium 読書会、参加してよいか聞いたほうがいいでしょうか? @yamachiii

**Comment by yamachiii** [comment]
すみませんまだ明日の打ち合わせの準備が終わらないんです。。。
だから聞かなくて大丈夫です。
ひとまずスラックに入れるか試してみます。

**Comment by masakura** [comment]
入れそうな感じです。

**Comment by yamachiii** [comment]
入れました！帰路で参加します！

**Comment by masakura** [comment]
お疲れ様でし。閉じますね。
